2024-01-24 12:24:13,696 INFO    StreamThr :211066 [internal.py:wandb_internal():86] W&B internal server running at pid: 211066, started at: 2024-01-24 12:24:13.695523
2024-01-24 12:24:13,698 DEBUG   HandlerThread:211066 [handler.py:handle_request():146] handle_request: status
2024-01-24 12:24:13,700 INFO    WriterThread:211066 [datastore.py:open_for_write():87] open: /media/ruben/data/documents/unief/thesis/thesis_manta_ray/wandb/run-20240124_122413-ib78uvdk/run-ib78uvdk.wandb
2024-01-24 12:24:13,703 DEBUG   SenderThread:211066 [sender.py:send():382] send: header
2024-01-24 12:24:13,709 DEBUG   SenderThread:211066 [sender.py:send():382] send: run
2024-01-24 12:24:17,384 INFO    SenderThread:211066 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f43cc971360>: Failed to resolve 'api.wandb.ai' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f43cc971360>: Failed to resolve 'api.wandb.ai' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/media/ruben/data/documents/unief/thesis/thesis_manta_ray/env/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f43cc971360>: Failed to resolve 'api.wandb.ai' ([Errno -3] Temporary failure in name resolution)"))
2024-01-24 12:24:18,712 DEBUG   HandlerThread:211066 [handler.py:handle_request():146] handle_request: keepalive
2024-01-24 12:24:23,715 DEBUG   HandlerThread:211066 [handler.py:handle_request():146] handle_request: keepalive
2024-01-24 12:24:28,717 DEBUG   HandlerThread:211066 [handler.py:handle_request():146] handle_request: keepalive
2024-01-24 12:24:33,719 DEBUG   HandlerThread:211066 [handler.py:handle_request():146] handle_request: keepalive
2024-01-24 12:24:38,722 DEBUG   HandlerThread:211066 [handler.py:handle_request():146] handle_request: keepalive
2024-01-24 12:24:43,724 DEBUG   HandlerThread:211066 [handler.py:handle_request():146] handle_request: keepalive
2024-01-24 12:24:48,727 DEBUG   HandlerThread:211066 [handler.py:handle_request():146] handle_request: keepalive
2024-01-24 12:24:53,730 DEBUG   HandlerThread:211066 [handler.py:handle_request():146] handle_request: keepalive
2024-01-24 12:24:58,732 DEBUG   HandlerThread:211066 [handler.py:handle_request():146] handle_request: keepalive
2024-01-24 12:25:03,734 DEBUG   HandlerThread:211066 [handler.py:handle_request():146] handle_request: keepalive
2024-01-24 12:25:08,736 DEBUG   HandlerThread:211066 [handler.py:handle_request():146] handle_request: keepalive
2024-01-24 12:25:10,910 DEBUG   HandlerThread:211066 [handler.py:handle_request():146] handle_request: shutdown
2024-01-24 12:25:10,910 INFO    HandlerThread:211066 [handler.py:finish():869] shutting down handler
2024-01-24 12:25:11,726 INFO    WriterThread:211066 [datastore.py:close():296] close: /media/ruben/data/documents/unief/thesis/thesis_manta_ray/wandb/run-20240124_122413-ib78uvdk/run-ib78uvdk.wandb
2024-01-24 12:25:24,779 INFO    SenderThread:211066 [dir_watcher.py:__init__():211] watching files in: /media/ruben/data/documents/unief/thesis/thesis_manta_ray/wandb/run-20240124_122413-ib78uvdk/files
2024-01-24 12:25:24,779 INFO    SenderThread:211066 [sender.py:_start_run_threads():1136] run started: ib78uvdk with start time 1706095453.695309
2024-01-24 12:25:24,779 INFO    SenderThread:211066 [sender.py:finish():1572] shutting down sender
2024-01-24 12:25:24,779 INFO    SenderThread:211066 [dir_watcher.py:finish():358] shutting down directory watcher
2024-01-24 12:25:25,780 INFO    SenderThread:211066 [dir_watcher.py:finish():388] scan: /media/ruben/data/documents/unief/thesis/thesis_manta_ray/wandb/run-20240124_122413-ib78uvdk/files
2024-01-24 12:25:25,780 INFO    SenderThread:211066 [dir_watcher.py:finish():402] scan save: /media/ruben/data/documents/unief/thesis/thesis_manta_ray/wandb/run-20240124_122413-ib78uvdk/files/config.yaml config.yaml
2024-01-24 12:25:25,781 INFO    SenderThread:211066 [file_pusher.py:finish():175] shutting down file pusher
2024-01-24 12:25:25,781 INFO    SenderThread:211066 [file_pusher.py:join():181] waiting for file pusher
2024-01-24 12:25:29,053 INFO    wandb-upload_0:211066 [upload_job.py:push():131] Uploaded file /media/ruben/data/documents/unief/thesis/thesis_manta_ray/wandb/run-20240124_122413-ib78uvdk/files/config.yaml
2024-01-24 12:25:29,286 INFO    SenderThread:211066 [file_stream.py:finish():595] file stream finish called
2024-01-24 12:25:30,719 INFO    SenderThread:211066 [file_stream.py:finish():599] file stream finish is done
